spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/salonview?serverTimezone=Asia/Seoul
    username: salonview
    password: salonview


logging.level:
  org.hibernate.SQL: debug